import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import { classifyEnvironmentLanguage, formatEnvironment, sanitizeInline, validateSnapshot } from '../lib/index.js'
const s={enabled:true,locale:'zh-CN',injectTime:true,injectTimezone:true,injectWeekday:true,injectWeather:true,showLocation:true,showCondition:true,showTemperature:true,showFeelsLike:true,showHumidity:true,showWind:true,weatherProvider:'open-meteo',locationMode:'manual',reverseGeocodingProvider:'auto',manualLocation:'武汉',weatherRefreshMinutes:30,locationRefreshMinutes:10,injectBattery:true,showCharging:true,injectDevice:true,showDeviceName:true,showDeviceModel:true,showDevicePlatform:true,customDeviceName:'我的电脑',sectionOrder:20}
assert.equal(sanitizeInline('<x>\n model'),'x model');assert.equal(validateSnapshot({capturedAt:'bad'}),null);assert.equal(classifyEnvironmentLanguage('cmn-CN'),'zh');assert.equal(classifyEnvironmentLanguage('zhx'),'en');assert.equal(classifyEnvironmentLanguage('not_a_locale'),undefined)
const text=formatEnvironment({capturedAt:'2026-01-01T00:00:00Z',locale:'zh-Hant',time:{timeZone:'Asia/Shanghai'},location:{label:'武汉 / 湖北 / 中国'},weather:{condition:'晴',temperature:30,feelsLike:35,humidity:80,windSpeed:8,windDirection:'北'},battery:{percentage:100,charging:true},device:{platform:'Windows'}},s,new Date('2026-08-18T13:00:00Z'))
for(const part of['【现实环境信息】','地点：武汉 / 湖北 / 中国','天气：晴','温度：30°C（体感：35°C）','湿度：80%','电量：100%','设备名称：我的电脑'])assert.ok(text.includes(part),`Chinese prompt missing ${part}`)
const english=formatEnvironment({capturedAt:'2026-01-01T00:00:00Z',locale:'fr-FR',time:{timeZone:'Europe/Paris'},location:{label:'Paris / Île-de-France / France'},weather:{condition:'Clear sky',temperature:24,feelsLike:25,humidity:45,windSpeed:12,windDirection:'NW'},battery:{percentage:80,charging:false},device:{name:'WORKSTATION',model:'Example Model',platform:'Windows 11'}},{...s,customDeviceName:''},new Date('2026-08-18T13:00:00Z'))
for(const part of['[Current environment]','Local time:','Time zone: Europe/Paris','Weekday: Tuesday','Location: Paris / Île-de-France / France','Weather: Clear sky','Temperature: 24°C (feels like 25°C)','Humidity: 45%','Wind: 12 km/h NW','Battery: 80%','Charging: no','Name: WORKSTATION'])assert.ok(english.includes(part),`English prompt missing ${part}`)
assert.ok(!english.includes('【现实环境信息】'),'non-Chinese browser locale must not use Chinese injection')
const bundle=await fs.readFile(new URL('../lib/client.cjs',import.meta.url),'utf8');for(const part of['open-meteo','met-norway','wttr.in','nominatim','bigdatacloud','photon','settings.section','立即测试并强制刷新','navigator.language','formatEnvironment(snapshot, s)'])assert.ok(bundle.includes(part),`bundle missing ${part}`);assert.ok(!bundle.includes('注入位置'),'obsolete placement setting remains')
const pkg=JSON.parse(await fs.readFile(new URL('../package.json',import.meta.url),'utf8'));assert.equal(pkg.exports['./package.json'],'./package.json');console.log('full migration tests passed')
