import assert from 'node:assert/strict'
import { createStatusService } from '../src/client/weather.js'
const calls=[]
const service=createStatusService({requestJson:async url=>{calls.push(url.hostname);if(url.hostname==='geocoding-api.open-meteo.com')return{results:[{name:'武汉',admin1:'湖北',country:'中国',latitude:30.59,longitude:114.3,timezone:'Asia/Shanghai'}]};if(url.hostname==='api.met.no')throw new Error('MET offline');if(url.hostname==='api.open-meteo.com')return{timezone:'Asia/Shanghai',current:{weather_code:0,temperature_2m:30,apparent_temperature:35,relative_humidity_2m:80,wind_speed_10m:8,wind_direction_10m:0}};throw new Error(`unexpected ${url}`)}})
const fallback=await service({weather:'1',locale:'zh-CN',provider:'met-norway',locationMode:'manual',location:'武汉',force:'1'});assert.equal(fallback.weather.source,'Open-Meteo');assert.equal(fallback.weather.fallbackFrom,'met-norway');assert.equal(fallback.weather.condition,'晴');assert.deepEqual(calls,['geocoding-api.open-meteo.com','api.met.no','api.open-meteo.com'])
const english=createStatusService({requestJson:async url=>{if(url.hostname==='geocoding-api.open-meteo.com'){assert.equal(url.searchParams.get('language'),'en');return{results:[{name:'Wuhan',admin1:'Hubei',country:'China',latitude:30.59,longitude:114.3,timezone:'Asia/Shanghai'}]}};if(url.hostname==='api.open-meteo.com')return{timezone:'Asia/Shanghai',current:{weather_code:51,temperature_2m:30,apparent_temperature:35,relative_humidity_2m:80,wind_speed_10m:8,wind_direction_10m:45}};throw new Error(`unexpected ${url}`)}})
const englishStatus=await english({weather:'1',locale:'en-US',provider:'open-meteo',locationMode:'manual',location:'Wuhan',force:'1'});assert.equal(englishStatus.location.label,'Wuhan / Hubei / China');assert.equal(englishStatus.weather.condition,'Light drizzle');assert.equal(englishStatus.weather.windDirection,'NE')
const localizedCalls=[]
const localized=createStatusService({requestJson:async url=>{localizedCalls.push(`${url.hostname}:${url.searchParams.get('language')||'-'}`);if(url.hostname==='geocoding-api.open-meteo.com'){const zh=url.searchParams.get('language')==='zh';return{results:[{name:zh?'武汉':'Wuhan',admin1:zh?'湖北':'Hubei',country:zh?'中国':'China',latitude:30.59,longitude:114.3,timezone:'Asia/Shanghai'}]}};if(url.hostname==='api.open-meteo.com')return{timezone:'Asia/Shanghai',current:{weather_code:2,temperature_2m:30,apparent_temperature:35,relative_humidity_2m:80,wind_speed_10m:8,wind_direction_10m:45}};throw new Error(`unexpected ${url}`)}})
const localizedZh=await localized({weather:'1',locale:'cmn-CN',provider:'open-meteo',locationMode:'manual',location:'Wuhan'}),localizedEn=await localized({weather:'1',locale:'zhx',provider:'open-meteo',locationMode:'manual',location:'Wuhan'});assert.equal(localizedZh.location.label,'武汉 / 湖北 / 中国');assert.equal(localizedZh.weather.condition,'局部多云');assert.equal(localizedEn.location.label,'Wuhan / Hubei / China');assert.equal(localizedEn.weather.condition,'Partly cloudy');assert.deepEqual(localizedCalls,['geocoding-api.open-meteo.com:zh','api.open-meteo.com:-','geocoding-api.open-meteo.com:en','api.open-meteo.com:-'])
const reverse=[]
const auto=createStatusService({requestJson:async url=>{if(url.hostname==='nominatim.openstreetmap.org'){reverse.push('nominatim');throw new Error('offline')};if(url.hostname==='api.bigdatacloud.net'){reverse.push('bigdatacloud');throw new Error('offline')};if(url.hostname==='photon.komoot.io'){reverse.push('photon');return{features:[{properties:{city:'宜昌市',state:'湖北省',country:'中国'}}]}};if(url.hostname==='api.open-meteo.com')return{timezone:'Asia/Shanghai',current:{weather_code:0,temperature_2m:30,apparent_temperature:35,relative_humidity_2m:80,wind_speed_10m:8,wind_direction_10m:0}};throw new Error(`unexpected ${url}`)}})
const status=await auto({weather:'1',provider:'open-meteo',locationMode:'auto',reverseGeocodingProvider:'auto',latitude:'30.66',longitude:'111.43',force:'1'});assert.deepEqual(reverse,['nominatim','bigdatacloud','photon']);assert.equal(status.location.addressProvider,'photon');console.log('weather and reverse fallback tests passed')
